spring:
  application:
    name: resistors

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:5174
